apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  labels:
    app: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: https://hub.docker.com/repository/docker/shumet/node-app
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        volumeMounts:
        - name: app-volume
          mountPath: /usr/src/app
        command: ["npm", "start"]
      volumes:
      - name: app-volume
        emptyDir: {}
